### ISSUE TITLE
I ran your program, but the results were too biased and not ideal.

### ISSUE THREAD

**Issue by xiaoqinghuang** [yuanxiaosc/Deep_dynamic_word_representation#1]
{"exact_match": 67.360454115421, "f1": 76.8968529039238}

**Comment by yuanxiaosc** [comment]
> {"exact_match": 67.360454115421, "f1": 76.8968529039238}

You are right! If the default parameters of BERT are used, the experimental results are almost the same as those of BERT. The new model can reach F1:88.76 by hyperparametric search and slightly changing the model output. In the near future, I will update the code and create a new, more user-friendly BERT resource.

**Comment by xiaoqinghuang** [comment]
如果是这样的话，run_squad_elmo有什么意义呢？仅仅将原来使用最后一层改为使用所有的层的权重和。我之前以为是将【真正】的ELMo和BERT结合了！

**Comment by yuanxiaosc** [comment]
> 如果是这样的话，run_squad_elmo有什么意义呢？仅仅将原来使用最后一层改为使用所有的层的权重和。我之前以为是将【真正】的ELMo和BERT结合了！

十分抱歉，这份资源确实仅仅只将 BERT 的多层双向Transformer模型与ELMo使用多层Bi-LSTM内部状态加权和的思想结合起来。如果想尝试其他方式结合效果，需要按照BERT论文中方法：先使用这个模型在大规模文本上预先训练，然后再在具体任务上微调。
